name: Neptune
services:
    neptune:
        container_name: neptune
        build: .
        environment:
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_URL=${AUTH_URL}
            - ALLOW_SIGNUPS=${ALLOW_SIGNUPS}
        volumes:
            - db:/app/data/
        env_file: ".env"
volumes:
    db:
