allowBuilds:
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "@js-temporal/polyfill": "npm:temporal-polyfill@^0.3.0"
patchedDependencies:
  '@fullcalendar/rrule': patches/@fullcalendar__rrule.patch
